spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/back
    username: sa
    passwrod:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
